# docker-compose.yml
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
    volumes:
      - ./vw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - ${HTTP_PORT}:80  # Needed for the ACME HTTP-01 challenge.
      - ${HTTPS_PORT}:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      DOMAIN: ${DOMAIN} #"https://vaultwarden.example.com"  # Your domain.
      EMAIL: ${EMAIL} #"admin@example.com"                 # The email address to use for ACME registration.
      LOG_FILE: "/data/access.log"
